name: 'TwitterBannerAction'
description: 'Post a tweet when new release is out.'
author: 'Rajvir Singh'
inputs:
  repo-content-object:
    description: Object for gathering information from github api about the project for showing in the banner.
  status:
    description: The status ("tweet") to post to twitter.
  consumer-key:
    description: >
      Consumer API key, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  consumer-secret:
    description: >
      Consumer API secret key, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  access-token:
    description: >
      Application access token, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  access-token-secret:
    description: >
      Application access token secret, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
runs:
  using: 'node12'
  main: './dist/index.js'